### ISSUE TITLE
Cannot open default.style in Mac.

### ISSUE THREAD

**Issue by itzMeerkat** [Kreogist/Cuties#8]
The reason is qApp->applicationDirPath returns current dir + "Cuties.app/contents/MacOS".
I'm working on it.

**Comment by itzMeerkat** [comment]
BTW I didn't try to pack it in to a pkg file, I just run from source code.

**Comment by itzMeerkat** [comment]
I think I'd better pack it into pkg....

**Comment by Harinlen** [comment]
Eh...It is my job to work on porting the application to Mac platform. However, we didn't spend time on this project further more (due to our time). Maybe it is time to restart this project?

**Comment by itzMeerkat** [comment]
那个。。所有下载链接都过期了。。可以续一下嘛。。

## 

At 2016-09-30 09:18:07, "Tojo Saki" notifications@github.com wrote:

Eh...It is my job to work on porting the application to Mac platform. However, we didn't spend time on this project further more (due to our time). Maybe it is time to restart this project?

**Comment by Harinlen** [comment]
啥？这……大概我们自己也没留着吧。也许百度云上还剩下几个版本。

**Comment by frantic1048** [comment]
@AG3 不是 Release 上还有咩？

**Comment by itzMeerkat** [comment]
我去找找.......忘这茬了XD
Sent from Mail Master
在2016年10月05日 01:52，Jiahao Guo 写道:

@AG3 不是 Release 上还有咩？
